"""P2#14：路由聚合层。

集中暴露所有 APIRouter，消除 main.py 中逐文件 import + include_router 的重复，
新增路由模块时只需在此登记一次，main.py 自动统一挂载到 API_V1_PREFIX 下。
"""
from app.api import (
    admin,
    affiliate,
    agent,
    ai,
    auth,
    banners,
    cart,
    categories,
    coupons,
    decoration,
    favorites,
    follow,
    health,
    images,
    inventory,
    invoices,
    knowledge,
    live,
    marketing,
    merchant,
    notes,
    notifications,
    orders,
    plus,
    points,
    presale,
    products,
    promotions,
    qna,
    recommendations,
    report,
    rewards,
    reviews,
    search,
    shops,
    staff,
    support,
    upload,
    users,
    variant,
    views,
    ws,
    shipping,
    payments,
)

# 所有业务路由统一前缀（与 main.py 原 include_router(prefix=API_V1_PREFIX) 行为一致）
ALL_ROUTERS = [
    health.router,
    auth.router,
    categories.router,
    products.router,
    reviews.router,
    cart.router,
    orders.router,
    ai.router,
    merchant.router,
    admin.router,
    coupons.router,
    favorites.router,
    notifications.router,
    points.router,
    recommendations.router,
    support.router,
    shops.router,
    banners.router,
    promotions.router,
    users.router,
    rewards.router,
    inventory.router,
    search.router,
    variant.router,
    follow.router,
    ws.router,
    shipping.router,
    payments.router,
    agent.router,
    marketing.router,
    decoration.router,
    notes.router,
    plus.router,
    qna.router,
    views.router,
    knowledge.router,
    affiliate.router,
    live.router,
    invoices.router,
    presale.router,
    images.router,
    upload.router,
    staff.router,
    report.router,
]

# 需要额外暴露的模块级符号（供 main.py 挂载静态目录）
UPLOAD_DIR = upload.UPLOAD_DIR
