# 商品图 URL 映射（Wikimedia Commons，CC 授权，可合法使用）。
# 由 seed 脚本按关键词预抓取生成；运行时直接使用，不依赖联网。
# 未命中关键词回退到 loremflickr。
COMMONS_IMGS = {
    'adapter': 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/Baseus_CCCP20UE_20W_USB_charger-1.jpg/1280px-Baseus_CCCP20UE_20W_USB_charger-1.jpg',
    'badge': 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/2023_M%C5%82odzie%C5%BCowa_Odznaka_Sprawno%C5%9Bci_Obronnej.jpg/1280px-2023_M%C5%82odzie%C5%BCowa_Odznaka_Sprawno%C5%9Bci_Obronnej.jpg',
    'bath mat': 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Ebing_Kunststoffmatten-20160429-RM-160135.jpg/1280px-Ebing_Kunststoffmatten-20160429-RM-160135.jpg',
    'bedding': 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/Bed_head.jpg/1280px-Bed_head.jpg',
    'bedsheet': 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Bed_in_Seattle_hotel.jpg/1280px-Bed_in_Seattle_hotel.jpg',
    'blanket': 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/71/3_packs_of_Leader_Super_Deluxe_Wool_Blanket_20210207.jpg/1280px-3_packs_of_Leader_Super_Deluxe_Wool_Blanket_20210207.jpg',
    'bluetooth speaker': 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Bluetooth_speaker_JBL_Xtreme_from_side_showing_one_of_the_bass_speakers.jpg/1280px-Bluetooth_speaker_JBL_Xtreme_from_side_showing_one_of_the_bass_speakers.jpg',
    'book': 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/13-11-02-olb-by-RalfR-03.jpg/1280px-13-11-02-olb-by-RalfR-03.jpg',
    'box': 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/33/Antarctica_-_South_Pole_Cardboard_Box_%22Disc_Golf_-_Gym%22.jpg/1280px-Antarctica_-_South_Pole_Cardboard_Box_%22Disc_Golf_-_Gym%22.jpg',
    'cable': 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/58/Cable_Mini_USB.jpg/1280px-Cable_Mini_USB.jpg',
    'camera': 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9b/Agfa_Click_BW_1.JPG/1280px-Agfa_Click_BW_1.JPG',
    'camera tripod': 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/%28Photography_equipment_Tripod_Photo_Camera_Tripod_photograph_in_a_studio%29.jpg/1280px-%28Photography_equipment_Tripod_Photo_Camera_Tripod_photograph_in_a_studio%29.jpg',
    'candle': 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Candle_%28Slava_celebration%29.jpg/1280px-Candle_%28Slava_celebration%29.jpg',
    'candle light': 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Candle_%28Slava_celebration%29.jpg/1280px-Candle_%28Slava_celebration%29.jpg',
    'canvas bag': 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/%22Votes_For_Women%22_Canvas_Bag%2C_ca._1920_%284359286695%29.jpg/1280px-%22Votes_For_Women%22_Canvas_Bag%2C_ca._1920_%284359286695%29.jpg',
    'charger': 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/76/1.5V_Lithium_Battery_Charger_and_Cable_Back_Picture.png/1280px-1.5V_Lithium_Battery_Charger_and_Cable_Back_Picture.png',
    'coffee pot': 'https://upload.wikimedia.org/wikipedia/commons/6/6d/Arab_Coffee_Pot.png',
    'coloring book': 'https://upload.wikimedia.org/wikipedia/commons/a/ae/Calvin_and_the_Colonel_-_A_Coloring_Book_%281962%29_-_Front_Cover.jpg',
    'coupon': 'https://upload.wikimedia.org/wikipedia/commons/5/58/CNET-Coupons-wikidata.png',
    'craft': 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Atl%C4%B1han_Handicraft_Market%2C_Odunpazar%C4%B1%2C_Eski%C5%9Fehir%2C_Turkey_01.jpg/1280px-Atl%C4%B1han_Handicraft_Market%2C_Odunpazar%C4%B1%2C_Eski%C5%9Fehir%2C_Turkey_01.jpg',
    'cushion': 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Coccix_Cushion.jpg/1280px-Coccix_Cushion.jpg',
    'desk lamp': 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/-44_Light_fixture.jpg/1280px--44_Light_fixture.jpg',
    'earbuds': 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1d/Earphones_BW_2011-12-10_15-49-08.JPG/1280px-Earphones_BW_2011-12-10_15-49-08.JPG',
    'embroidery': 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/Blue_mural_embroidery%2C_Udaipur%2C_Rajasthan%2C_India.jpg/1280px-Blue_mural_embroidery%2C_Udaipur%2C_Rajasthan%2C_India.jpg',
    'felt': 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/FELTED_FIGURE_-_EXHIBITION_AT_SEN_2017.jpg/1280px-FELTED_FIGURE_-_EXHIBITION_AT_SEN_2017.jpg',
    'film camera': 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Ensign_Midget_-_model_22_camera_in_comparison_to_a_type_135_film_roll.jpg/1280px-Ensign_Midget_-_model_22_camera_in_comparison_to_a_type_135_film_roll.jpg',
    'fitness band': 'https://upload.wikimedia.org/wikipedia/commons/6/6c/Charge_3_%28cropped%29.jpg',
    'floor lamp': 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/ff/Standing_Lamp_with_Running_Dogs_MET_DP123788.jpg/1280px-Standing_Lamp_with_Running_Dogs_MET_DP123788.jpg',
    'flower pot': 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/3D_printed_flower_pots.jpg/1280px-3D_printed_flower_pots.jpg',
    'fridge magnet': 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Bellen_-_Melitta_refrigerator_magnet_%282019%29.jpg/1280px-Bellen_-_Melitta_refrigerator_magnet_%282019%29.jpg',
    'frying pan': 'https://upload.wikimedia.org/wikipedia/commons/a/a1/Black_electric_frying_pan.png',
    'gaming headset': 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/RGB_gaming_headset_on_desk_with_ambient_lighting.jpg/1280px-RGB_gaming_headset_on_desk_with_ambient_lighting.jpg',
    'gift': 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/Gift_box_containing_Dow_plastics_products_-_DPLA_-_1b6050e986bd8130742d8870aad7da36.jpg/1280px-Gift_box_containing_Dow_plastics_products_-_DPLA_-_1b6050e986bd8130742d8870aad7da36.jpg',
    'headphone': 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1d/AudioQuest_NightHawk_Carbon_headphones_%2833582571334%29.jpg/1280px-AudioQuest_NightHawk_Carbon_headphones_%2833582571334%29.jpg',
    'headphones': 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1d/AudioQuest_NightHawk_Carbon_headphones_%2833582571334%29.jpg/1280px-AudioQuest_NightHawk_Carbon_headphones_%2833582571334%29.jpg',
    'headset': 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/Bluetooth_headset_WEP-200-8934.jpg/1280px-Bluetooth_headset_WEP-200-8934.jpg',
    'ipad stand': 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/50/IPad_Wooden_Stand_-_TNW_Conference_2011_-_Day_2_%285669574792%29.jpg/1280px-IPad_Wooden_Stand_-_TNW_Conference_2011_-_Day_2_%285669574792%29.jpg',
    'jigsaw': 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/Jigsaw_puzzle_01_by_Scouten.jpg/1280px-Jigsaw_puzzle_01_by_Scouten.jpg',
    'journal': 'https://upload.wikimedia.org/wikipedia/commons/a/a4/Cellular%2C_Molecular_and_Biomedical_Reports.jpg',
    'key': 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Alfa_Romeo_keychain_which_came_with_an_Alfa_Romeo_33_in_the_1980s%2C_without_keys.jpg/1280px-Alfa_Romeo_keychain_which_came_with_an_Alfa_Romeo_33_in_the_1980s%2C_without_keys.jpg',
    'keyboard': 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7f/Beautiful_Mechanical_Keyboard.jpg/1280px-Beautiful_Mechanical_Keyboard.jpg',
    'keychain': 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Alfa_Romeo_keychain_which_came_with_an_Alfa_Romeo_33_in_the_1980s%2C_without_keys.jpg/1280px-Alfa_Romeo_keychain_which_came_with_an_Alfa_Romeo_33_in_the_1980s%2C_without_keys.jpg',
    'knit': 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/%22Wrap_with_Love%22_blanket.jpg/1280px-%22Wrap_with_Love%22_blanket.jpg',
    'lamp': 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/82/2026.06.05_USSR_Milk_Glass_Table_Lamp_01.jpg/1280px-2026.06.05_USSR_Milk_Glass_Table_Lamp_01.jpg',
    'magazine': 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b2/Kazoo_Magazine%2C_Issue_24.jpg/1280px-Kazoo_Magazine%2C_Issue_24.jpg',
    'magnet': 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Bellen_-_Melitta_refrigerator_magnet_%282019%29.jpg/1280px-Bellen_-_Melitta_refrigerator_magnet_%282019%29.jpg',
    'mechanical keyboard': 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7f/Beautiful_Mechanical_Keyboard.jpg/1280px-Beautiful_Mechanical_Keyboard.jpg',
    'memo': 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/AT%26T_Bell_Laboratories_memo_of_call_pad.jpg/1280px-AT%26T_Bell_Laboratories_memo_of_call_pad.jpg',
    'mousepad': 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/Philips-CDi-Mouse-wPad.jpg/1280px-Philips-CDi-Mouse-wPad.jpg',
    'notebook': 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/Kierkegaard%27s_Journals_and_Notebooks%2C_Volume_03_-_Notebooks_1-15.jpg/1280px-Kierkegaard%27s_Journals_and_Notebooks%2C_Volume_03_-_Notebooks_1-15.jpg',
    'organizer': 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Drawing%2C_Design_for_Desk_Organizer_in_Plan_and_Elevation%2C_1900%E2%80%9305_%28CH_18684163%29.jpg/1280px-Drawing%2C_Design_for_Desk_Organizer_in_Plan_and_Elevation%2C_1900%E2%80%9305_%28CH_18684163%29.jpg',
    'pan': 'https://upload.wikimedia.org/wikipedia/commons/a/a1/Black_electric_frying_pan.png',
    'pen': 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ed/A_pen_writing_%22Example%22.jpg/1280px-A_pen_writing_%22Example%22.jpg',
    'pillow': 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Pillows_on_a_hotel_bed.jpg/1280px-Pillows_on_a_hotel_bed.jpg',
    'pin': 'https://upload.wikimedia.org/wikipedia/commons/d/dc/119th_United_States_Congress_lapel_pin.jpg',
    'plant': 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/69/%28MHNT%29_Sedum_spathulifolium_-_Habitus.jpg/1280px-%28MHNT%29_Sedum_spathulifolium_-_Habitus.jpg',
    'planter': 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/3D_printed_flower_pots.jpg/1280px-3D_printed_flower_pots.jpg',
    'plate': 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/13-09-01-kochtreffen-wien-RalfR-02.jpg/1280px-13-09-01-kochtreffen-wien-RalfR-02.jpg',
    'portable speaker': 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Beats_By_Dr._Dre_Pill_Portable_Bluetooth_Speaker_Black_N2.jpg/1280px-Beats_By_Dr._Dre_Pill_Portable_Bluetooth_Speaker_Black_N2.jpg',
    'pour coffee': 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Caf%C3%A9_coado.jpg/1280px-Caf%C3%A9_coado.jpg',
    'present': 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/ff/Diwali_gift.jpg/1280px-Diwali_gift.jpg',
    'puzzle': 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/Jigsaw_puzzle_01_by_Scouten.jpg/1280px-Jigsaw_puzzle_01_by_Scouten.jpg',
    'record': 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/02024_1054_Vinyl_records_in_Bielsko-Bia%C5%82a.jpg/1280px-02024_1054_Vinyl_records_in_Bielsko-Bia%C5%82a.jpg',
    'ring': 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/db/Gold_rings_and_other_jewelry%2C_Aidonia%2C_AM_of_Nemea%2C_201947.jpg/1280px-Gold_rings_and_other_jewelry%2C_Aidonia%2C_AM_of_Nemea%2C_201947.jpg',
    'ring light': 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ed/4-quadrant_ring_light_controller.jpg/1280px-4-quadrant_ring_light_controller.jpg',
    'rug': 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Ebing_Kunststoffmatten-20160429-RM-160135.jpg/1280px-Ebing_Kunststoffmatten-20160429-RM-160135.jpg',
    'sale': 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/Alcohol_disinfectant_and_masks_for_sale_at_the_entrance_of_a_liquor_shop.jpg/1280px-Alcohol_disinfectant_and_masks_for_sale_at_the_entrance_of_a_liquor_shop.jpg',
    'scented candle': 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Candle_%28Slava_celebration%29.jpg/1280px-Candle_%28Slava_celebration%29.jpg',
    'shelf': 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/13-11-02-olb-by-RalfR-03.jpg/1280px-13-11-02-olb-by-RalfR-03.jpg',
    'smart ring': 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/MOTA_Smart_Ring_%2816241008234%29.jpg/1280px-MOTA_Smart_Ring_%2816241008234%29.jpg',
    'smartwatch': 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Black_Olio_Brown_Leather_Strap_Front.jpg/1280px-Black_Olio_Brown_Leather_Strap_Front.jpg',
    'speaker': 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Bluetooth_speaker_JBL_Xtreme_from_side_showing_one_of_the_bass_speakers.jpg/1280px-Bluetooth_speaker_JBL_Xtreme_from_side_showing_one_of_the_bass_speakers.jpg',
    'stationery': 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/Assorted_Stationery_Display_Case.jpg/1280px-Assorted_Stationery_Display_Case.jpg',
    'sticker': 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/Hackover_2023_Sticker_Box.jpg/1280px-Hackover_2023_Sticker_Box.jpg',
    'sticky note': 'https://upload.wikimedia.org/wikipedia/commons/d/d9/Post-it.jpg',
    'storage': 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Box_of_Marbles.jpg/1280px-Box_of_Marbles.jpg',
    'storage bag': 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/97/America%2C_Native_North_American%2C_Plains%2C_Lakota_%28Sioux%29_people%2C_Post_contact_-_Storage_Bag_-_1937.850_-_Cleveland_Museum_of_Art.tif/lossy-page1-1280px-America%2C_Native_North_American%2C_Plains%2C_Lakota_%28Sioux%29_people%2C_Post_contact_-_Storage_Bag_-_1937.850_-_Cleveland_Museum_of_Art.tif.jpg',
    'storage box': 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Box_of_Marbles.jpg/1280px-Box_of_Marbles.jpg',
    'streaming': 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/af/Cytoplasmic_streaming.webm/1280px--Cytoplasmic_streaming.webm.jpg',
    'studio light': 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Blitzanlage.jpg/1280px-Blitzanlage.jpg',
    'tablet stand': 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/DIY_tablet_smartphone_stand_1.jpg/1280px-DIY_tablet_smartphone_stand_1.jpg',
    'tableware': 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/001_Table_Setting_Close_Up_2_0001.jpg/1280px-001_Table_Setting_Close_Up_2_0001.jpg',
    'tape': 'https://upload.wikimedia.org/wikipedia/commons/7/7e/Masking-tape.png',
    'terrarium': 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/A_terrarium_containing_a_fern_and_a_light_source.jpg/1280px-A_terrarium_containing_a_fern_and_a_light_source.jpg',
    'tote bag': 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/ESEAP_Conference_2024_tote_bag_with_contents.jpg/1280px-ESEAP_Conference_2024_tote_bag_with_contents.jpg',
    'tripod': 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/%28Photography_equipment_Tripod_Photo_Camera_Tripod_photograph_in_a_studio%29.jpg/1280px-%28Photography_equipment_Tripod_Photo_Camera_Tripod_photograph_in_a_studio%29.jpg',
    'usb cable': 'https://upload.wikimedia.org/wikipedia/commons/c/c3/Braid_and_foil_shielded_usb_cable.jpg',
    'usb hub': 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/2023_Hub_USB_2.0.jpg/1280px-2023_Hub_USB_2.0.jpg',
    'vinyl': 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/02024_1054_Vinyl_records_in_Bielsko-Bia%C5%82a.jpg/1280px-02024_1054_Vinyl_records_in_Bielsko-Bia%C5%82a.jpg',
    'washi tape': 'https://upload.wikimedia.org/wikipedia/commons/7/7e/Masking-tape.png',
    'watch': 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/Casio_Wrist_Watch_01.jpg/1280px-Casio_Wrist_Watch_01.jpg',
    'webcam': 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Asus_Zenbook_UX32V_-_webcam_module-9649.jpg/1280px-Asus_Zenbook_UX32V_-_webcam_module-9649.jpg',
    'wireless charger': 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/Inductive_charging_efficiency.jpg/1280px-Inductive_charging_efficiency.jpg',
    'wristband': 'https://upload.wikimedia.org/wikipedia/commons/6/6c/Charge_3_%28cropped%29.jpg',
    'usb charger': 'https://upload.wikimedia.org/wikipedia/commons/a/a8/Apple_5W_USB_Power_Adapter_%284935%29.jpg',
    'powerbank': 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7c/Power_bank.JPG/1280px-Power_bank.JPG',
    'storage basket': 'https://upload.wikimedia.org/wikipedia/commons/1/1c/A_weaved_basket.jpg',
    'storage rack': 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/African_Studies_Bookshelf.jpg/1280px-African_Studies_Bookshelf.jpg',
    'desk shelf': 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7d/Music_shelf_-_Jaspers_3D_3-tiers_keyboard_stand_with_homemade_wooden_shelves_%28by_David_J%29.jpg/1280px-Music_shelf_-_Jaspers_3D_3-tiers_keyboard_stand_with_homemade_wooden_shelves_%28by_David_J%29.jpg',
    'hanging organizer': 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/HANGING_ORGANIZER_By_Tisha_Sy.jpg/1280px-HANGING_ORGANIZER_By_Tisha_Sy.jpg',
    'duvet cover': 'https://upload.wikimedia.org/wikipedia/commons/e/e6/Coastal_East_Lothian_%2C_Have_Ye_No_Changed_A_Duvet_Cover_Before%5E_-_geograph.org.uk_-_3471221.jpg',
}
